# Default values for name-resolution-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deployment:
  replicaCount: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      # This setting allows one existing pod to be taken down before new ones are up and running.
      # It means there could be a brief period where fewer pods are available during the update.
      maxUnavailable: 1
      # This setting does not allow any additional pods above the desired number of replicas during the update.
      # A new pod will only be created after an old pod is taken down.
      maxSurge: 0
image:
  repository: 853771734544.dkr.ecr.us-east-1.amazonaws.com/translator-name-resolution-api
  # Overrides the image tag whose default is the chart appVersion.
  tag: DOCKER_VERSION_VALUE
  pullPolicy: Always

containers:
  name: nameres
  port: 9000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/tags: Name=NAMERES_ALB_TAG_VALUE,Environment=ENVIRONMENT_TAG_VALUE
    alb.ingress.kubernetes.io/security-groups: NAMERES_ALB_SG_VALUE
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-2-Ext-2018-06
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/success-codes: '200'
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=600
  host: NAMERES_HOSTNAME_VALUE

ncats:
  labels:
    gov.nih.ncats.appenv: appenv
    gov.nih.ncats.appname: translator-name-resolution-api
    gov.nih.ncats.appentry: NAMERES_HOSTNAME_VALUE
    gov.nih.ncats.appentrytype: https
    gov.nih.ncats.appentryport: tcp

# With the following two sections, we can restrict the deployment on and only on the specific node
# toleration to node taint such that this deployment can be scheduled on the tainted node while others without the toleration can not
tolerations: 
- key      : "transltr"
  value    : "nodenorm"
  operator : "Equal"
  effect   : "NoSchedule"

# nodeSelection affinity(application=nodenorm) such that this deployment will only select the node with that label
affinity: 
  # this ensures pod only runs on node with label application=nodenorm
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: application
          operator: In
          values:
          - nodenorm
  # this ensures only ONE pod will run on each node
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
        - key: app.kubernetes.io/name
          operator: In
          values:
          - nameres
      topologyKey: "kubernetes.io/hostname"
